
// This file has been generated by the GUI designer. Do not modify.
namespace LAdd
{
	public partial class EmailDialog
	{
		private global::Gtk.Alignment GtkAlignment2;
		private global::Gtk.VBox vbox3;
		private global::Gtk.Label label1;
		private global::Gtk.Entry enFrom;
		private global::Gtk.Label label2;
		private global::Gtk.Entry enTo;
		private global::Gtk.Label labelSubject;
		private global::Gtk.ScrolledWindow GtkScrolledWindow;
		private global::Gtk.TextView tvSubject;
		private global::Gtk.Label labelStatus;
		private global::Gtk.Button buttonCancel;
		private global::Gtk.Button btnSendEmail;

		protected virtual void Build ()
		{
			global::Stetic.Gui.Initialize (this);
			// Widget LAdd.EmailDialog
			this.Name = "LAdd.EmailDialog";
			this.WindowPosition = ((global::Gtk.WindowPosition)(4));
			this.BorderWidth = ((uint)(6));
			// Internal child LAdd.EmailDialog.VBox
			global::Gtk.VBox w1 = this.VBox;
			w1.Name = "dialog1_VBox";
			w1.BorderWidth = ((uint)(2));
			// Container child dialog1_VBox.Gtk.Box+BoxChild
			this.GtkAlignment2 = new global::Gtk.Alignment (0F, 0F, 1F, 1F);
			this.GtkAlignment2.Name = "GtkAlignment2";
			this.GtkAlignment2.LeftPadding = ((uint)(12));
			// Container child GtkAlignment2.Gtk.Container+ContainerChild
			this.vbox3 = new global::Gtk.VBox ();
			this.vbox3.Name = "vbox3";
			this.vbox3.Spacing = 6;
			// Container child vbox3.Gtk.Box+BoxChild
			this.label1 = new global::Gtk.Label ();
			this.label1.Name = "label1";
			this.label1.Xalign = 0F;
			this.label1.LabelProp = global::Mono.Unix.Catalog.GetString ("From");
			this.vbox3.Add (this.label1);
			global::Gtk.Box.BoxChild w2 = ((global::Gtk.Box.BoxChild)(this.vbox3 [this.label1]));
			w2.Position = 0;
			w2.Expand = false;
			w2.Fill = false;
			// Container child vbox3.Gtk.Box+BoxChild
			this.enFrom = new global::Gtk.Entry ();
			this.enFrom.CanFocus = true;
			this.enFrom.Name = "enFrom";
			this.enFrom.IsEditable = true;
			this.enFrom.InvisibleChar = '•';
			this.vbox3.Add (this.enFrom);
			global::Gtk.Box.BoxChild w3 = ((global::Gtk.Box.BoxChild)(this.vbox3 [this.enFrom]));
			w3.Position = 1;
			w3.Expand = false;
			w3.Fill = false;
			// Container child vbox3.Gtk.Box+BoxChild
			this.label2 = new global::Gtk.Label ();
			this.label2.Name = "label2";
			this.label2.Xalign = 0F;
			this.label2.LabelProp = global::Mono.Unix.Catalog.GetString ("To");
			this.vbox3.Add (this.label2);
			global::Gtk.Box.BoxChild w4 = ((global::Gtk.Box.BoxChild)(this.vbox3 [this.label2]));
			w4.Position = 2;
			w4.Expand = false;
			w4.Fill = false;
			// Container child vbox3.Gtk.Box+BoxChild
			this.enTo = new global::Gtk.Entry ();
			this.enTo.CanFocus = true;
			this.enTo.Name = "enTo";
			this.enTo.IsEditable = true;
			this.enTo.InvisibleChar = '•';
			this.vbox3.Add (this.enTo);
			global::Gtk.Box.BoxChild w5 = ((global::Gtk.Box.BoxChild)(this.vbox3 [this.enTo]));
			w5.Position = 3;
			w5.Expand = false;
			w5.Fill = false;
			// Container child vbox3.Gtk.Box+BoxChild
			this.labelSubject = new global::Gtk.Label ();
			this.labelSubject.Name = "labelSubject";
			this.labelSubject.Xalign = 0F;
			this.labelSubject.LabelProp = global::Mono.Unix.Catalog.GetString ("Subject");
			this.vbox3.Add (this.labelSubject);
			global::Gtk.Box.BoxChild w6 = ((global::Gtk.Box.BoxChild)(this.vbox3 [this.labelSubject]));
			w6.Position = 4;
			w6.Expand = false;
			w6.Fill = false;
			// Container child vbox3.Gtk.Box+BoxChild
			this.GtkScrolledWindow = new global::Gtk.ScrolledWindow ();
			this.GtkScrolledWindow.Name = "GtkScrolledWindow";
			this.GtkScrolledWindow.HscrollbarPolicy = ((global::Gtk.PolicyType)(2));
			this.GtkScrolledWindow.ShadowType = ((global::Gtk.ShadowType)(1));
			// Container child GtkScrolledWindow.Gtk.Container+ContainerChild
			this.tvSubject = new global::Gtk.TextView ();
			this.tvSubject.CanFocus = true;
			this.tvSubject.Name = "tvSubject";
			this.GtkScrolledWindow.Add (this.tvSubject);
			this.vbox3.Add (this.GtkScrolledWindow);
			global::Gtk.Box.BoxChild w8 = ((global::Gtk.Box.BoxChild)(this.vbox3 [this.GtkScrolledWindow]));
			w8.Position = 5;
			// Container child vbox3.Gtk.Box+BoxChild
			this.labelStatus = new global::Gtk.Label ();
			this.labelStatus.Name = "labelStatus";
			this.labelStatus.Xalign = 1F;
			this.vbox3.Add (this.labelStatus);
			global::Gtk.Box.BoxChild w9 = ((global::Gtk.Box.BoxChild)(this.vbox3 [this.labelStatus]));
			w9.Position = 6;
			w9.Expand = false;
			w9.Fill = false;
			this.GtkAlignment2.Add (this.vbox3);
			w1.Add (this.GtkAlignment2);
			global::Gtk.Box.BoxChild w11 = ((global::Gtk.Box.BoxChild)(w1 [this.GtkAlignment2]));
			w11.Position = 0;
			// Internal child LAdd.EmailDialog.ActionArea
			global::Gtk.HButtonBox w12 = this.ActionArea;
			w12.Name = "dialog1_ActionArea";
			w12.Spacing = 10;
			w12.BorderWidth = ((uint)(5));
			w12.LayoutStyle = ((global::Gtk.ButtonBoxStyle)(4));
			// Container child dialog1_ActionArea.Gtk.ButtonBox+ButtonBoxChild
			this.buttonCancel = new global::Gtk.Button ();
			this.buttonCancel.CanDefault = true;
			this.buttonCancel.CanFocus = true;
			this.buttonCancel.Name = "buttonCancel";
			this.buttonCancel.UseStock = true;
			this.buttonCancel.UseUnderline = true;
			this.buttonCancel.Label = "gtk-cancel";
			this.AddActionWidget (this.buttonCancel, -6);
			global::Gtk.ButtonBox.ButtonBoxChild w13 = ((global::Gtk.ButtonBox.ButtonBoxChild)(w12 [this.buttonCancel]));
			w13.Expand = false;
			w13.Fill = false;
			// Container child dialog1_ActionArea.Gtk.ButtonBox+ButtonBoxChild
			this.btnSendEmail = new global::Gtk.Button ();
			this.btnSendEmail.CanDefault = true;
			this.btnSendEmail.CanFocus = true;
			this.btnSendEmail.Name = "btnSendEmail";
			this.btnSendEmail.UseUnderline = true;
			this.btnSendEmail.Label = global::Mono.Unix.Catalog.GetString ("Send");
			this.AddActionWidget (this.btnSendEmail, -5);
			global::Gtk.ButtonBox.ButtonBoxChild w14 = ((global::Gtk.ButtonBox.ButtonBoxChild)(w12 [this.btnSendEmail]));
			w14.Position = 1;
			w14.Expand = false;
			w14.Fill = false;
			if ((this.Child != null)) {
				this.Child.ShowAll ();
			}
			this.DefaultWidth = 301;
			this.DefaultHeight = 270;
			this.Show ();
			this.btnSendEmail.Clicked += new global::System.EventHandler (this.onSendEmail);
		}
	}
}
