
// This file has been generated by the GUI designer. Do not modify.
public partial class MainWindow
{
	private global::Gtk.UIManager UIManager;
	private global::Gtk.Action pasteAction;
	private global::Gtk.Action closeAction;
	private global::Gtk.Action editAction;
	private global::Gtk.Action editLinkAction;
	private global::Gtk.Action editAction1;
	private global::Gtk.Action refreshAction;
	private global::Gtk.Action pasteAction1;
	private global::Gtk.Action editAction2;
	private global::Gtk.Action deleteAction;
	private global::Gtk.Action refreshAction1;
	private global::Gtk.VBox vbox1;
	private global::Gtk.HBox hbox2;
	private global::Gtk.Toolbar toolbarMain;
	private global::Gtk.Label labelTopStatus;
	private global::Gtk.Button btnChooseDb;
	private global::Gtk.Button btnShareDB;
	private global::Gtk.Frame frame1;
	private global::Gtk.Alignment GtkAlignment1;
	private global::Gtk.VBox vbox2;
	private global::Gtk.ScrolledWindow swLinks;
	private global::Gtk.Label labelStatus;
	private global::Gtk.HBox hbox1;
	private global::Gtk.ComboBox cbSearchFieldType;
	private global::Gtk.Entry searchEntry;
	private global::Gtk.ComboBox cbOnlySearchOnColumns;
	private global::Gtk.Label GtkLabelTitle;

	protected virtual void Build ()
	{
		global::Stetic.Gui.Initialize (this);
		// Widget MainWindow
		this.UIManager = new global::Gtk.UIManager ();
		global::Gtk.ActionGroup w1 = new global::Gtk.ActionGroup ("Default");
		this.pasteAction = new global::Gtk.Action ("pasteAction", null, global::Mono.Unix.Catalog.GetString ("Add a link"), "gtk-paste");
		w1.Add (this.pasteAction, null);
		this.closeAction = new global::Gtk.Action ("closeAction", null, global::Mono.Unix.Catalog.GetString ("Delete links"), "gtk-close");
		w1.Add (this.closeAction, null);
		this.editAction = new global::Gtk.Action ("editAction", null, null, "gtk-edit");
		w1.Add (this.editAction, null);
		this.editLinkAction = new global::Gtk.Action ("editLinkAction", null, global::Mono.Unix.Catalog.GetString ("Edit links"), "gtk-edit");
		w1.Add (this.editLinkAction, null);
		this.editAction1 = new global::Gtk.Action ("editAction1", null, null, "gtk-edit");
		w1.Add (this.editAction1, null);
		this.refreshAction = new global::Gtk.Action ("refreshAction", null, null, "gtk-refresh");
		w1.Add (this.refreshAction, null);
		this.pasteAction1 = new global::Gtk.Action ("pasteAction1", null, global::Mono.Unix.Catalog.GetString ("Add a link"), "gtk-paste");
		w1.Add (this.pasteAction1, null);
		this.editAction2 = new global::Gtk.Action ("editAction2", null, global::Mono.Unix.Catalog.GetString ("Edit links"), "gtk-edit");
		w1.Add (this.editAction2, null);
		this.deleteAction = new global::Gtk.Action ("deleteAction", null, global::Mono.Unix.Catalog.GetString ("Delete links"), "gtk-delete");
		w1.Add (this.deleteAction, null);
		this.refreshAction1 = new global::Gtk.Action ("refreshAction1", null, global::Mono.Unix.Catalog.GetString ("Update"), "gtk-refresh");
		w1.Add (this.refreshAction1, null);
		this.UIManager.InsertActionGroup (w1, 0);
		this.AddAccelGroup (this.UIManager.AccelGroup);
		this.Name = "MainWindow";
		this.Title = global::Mono.Unix.Catalog.GetString ("MainWindow");
		this.Icon = global::Stetic.IconLoader.LoadIcon (this, "stock_add-bookmark", global::Gtk.IconSize.Menu);
		this.WindowPosition = ((global::Gtk.WindowPosition)(4));
		// Container child MainWindow.Gtk.Container+ContainerChild
		this.vbox1 = new global::Gtk.VBox ();
		this.vbox1.Name = "vbox1";
		this.vbox1.Spacing = 6;
		// Container child vbox1.Gtk.Box+BoxChild
		this.hbox2 = new global::Gtk.HBox ();
		this.hbox2.Name = "hbox2";
		this.hbox2.Spacing = 6;
		// Container child hbox2.Gtk.Box+BoxChild
		this.UIManager.AddUiFromString ("<ui><toolbar name='toolbarMain'><toolitem name='pasteAction1' action='pasteAction1'/><toolitem name='editAction2' action='editAction2'/><toolitem name='deleteAction' action='deleteAction'/><toolitem name='refreshAction1' action='refreshAction1'/></toolbar></ui>");
		this.toolbarMain = ((global::Gtk.Toolbar)(this.UIManager.GetWidget ("/toolbarMain")));
		this.toolbarMain.Name = "toolbarMain";
		this.toolbarMain.ShowArrow = false;
		this.hbox2.Add (this.toolbarMain);
		global::Gtk.Box.BoxChild w2 = ((global::Gtk.Box.BoxChild)(this.hbox2 [this.toolbarMain]));
		w2.Position = 0;
		// Container child hbox2.Gtk.Box+BoxChild
		this.labelTopStatus = new global::Gtk.Label ();
		this.labelTopStatus.Name = "labelTopStatus";
		this.labelTopStatus.Xalign = 0F;
		this.hbox2.Add (this.labelTopStatus);
		global::Gtk.Box.BoxChild w3 = ((global::Gtk.Box.BoxChild)(this.hbox2 [this.labelTopStatus]));
		w3.Position = 1;
		// Container child hbox2.Gtk.Box+BoxChild
		this.btnChooseDb = new global::Gtk.Button ();
		this.btnChooseDb.CanFocus = true;
		this.btnChooseDb.Name = "btnChooseDb";
		this.btnChooseDb.UseUnderline = true;
		this.btnChooseDb.BorderWidth = ((uint)(6));
		this.btnChooseDb.Label = global::Mono.Unix.Catalog.GetString ("Database's");
		this.hbox2.Add (this.btnChooseDb);
		global::Gtk.Box.BoxChild w4 = ((global::Gtk.Box.BoxChild)(this.hbox2 [this.btnChooseDb]));
		w4.Position = 2;
		w4.Expand = false;
		w4.Fill = false;
		// Container child hbox2.Gtk.Box+BoxChild
		this.btnShareDB = new global::Gtk.Button ();
		this.btnShareDB.CanFocus = true;
		this.btnShareDB.Name = "btnShareDB";
		this.btnShareDB.UseUnderline = true;
		this.btnShareDB.BorderWidth = ((uint)(6));
		// Container child btnShareDB.Gtk.Container+ContainerChild
		global::Gtk.Alignment w5 = new global::Gtk.Alignment (0.5F, 0.5F, 0F, 0F);
		// Container child GtkAlignment.Gtk.Container+ContainerChild
		global::Gtk.HBox w6 = new global::Gtk.HBox ();
		w6.Spacing = 2;
		// Container child GtkHBox.Gtk.Container+ContainerChild
		global::Gtk.Image w7 = new global::Gtk.Image ();
		w7.Pixbuf = global::Stetic.IconLoader.LoadIcon (this, "stock_addressbook", global::Gtk.IconSize.Menu);
		w6.Add (w7);
		// Container child GtkHBox.Gtk.Container+ContainerChild
		global::Gtk.Label w9 = new global::Gtk.Label ();
		w9.LabelProp = global::Mono.Unix.Catalog.GetString ("Share");
		w9.UseUnderline = true;
		w6.Add (w9);
		w5.Add (w6);
		this.btnShareDB.Add (w5);
		this.hbox2.Add (this.btnShareDB);
		global::Gtk.Box.BoxChild w13 = ((global::Gtk.Box.BoxChild)(this.hbox2 [this.btnShareDB]));
		w13.Position = 3;
		w13.Expand = false;
		w13.Fill = false;
		this.vbox1.Add (this.hbox2);
		global::Gtk.Box.BoxChild w14 = ((global::Gtk.Box.BoxChild)(this.vbox1 [this.hbox2]));
		w14.Position = 0;
		w14.Expand = false;
		w14.Fill = false;
		// Container child vbox1.Gtk.Box+BoxChild
		this.frame1 = new global::Gtk.Frame ();
		this.frame1.Name = "frame1";
		this.frame1.ShadowType = ((global::Gtk.ShadowType)(0));
		this.frame1.BorderWidth = ((uint)(3));
		// Container child frame1.Gtk.Container+ContainerChild
		this.GtkAlignment1 = new global::Gtk.Alignment (0F, 0F, 1F, 1F);
		this.GtkAlignment1.Name = "GtkAlignment1";
		this.GtkAlignment1.LeftPadding = ((uint)(12));
		// Container child GtkAlignment1.Gtk.Container+ContainerChild
		this.vbox2 = new global::Gtk.VBox ();
		this.vbox2.Name = "vbox2";
		this.vbox2.Spacing = 6;
		// Container child vbox2.Gtk.Box+BoxChild
		this.swLinks = new global::Gtk.ScrolledWindow ();
		this.swLinks.CanFocus = true;
		this.swLinks.Name = "swLinks";
		this.swLinks.ShadowType = ((global::Gtk.ShadowType)(1));
		this.vbox2.Add (this.swLinks);
		global::Gtk.Box.BoxChild w15 = ((global::Gtk.Box.BoxChild)(this.vbox2 [this.swLinks]));
		w15.Position = 0;
		// Container child vbox2.Gtk.Box+BoxChild
		this.labelStatus = new global::Gtk.Label ();
		this.labelStatus.Name = "labelStatus";
		this.labelStatus.Xalign = 0F;
		this.labelStatus.Yalign = 0F;
		this.vbox2.Add (this.labelStatus);
		global::Gtk.Box.BoxChild w16 = ((global::Gtk.Box.BoxChild)(this.vbox2 [this.labelStatus]));
		w16.Position = 1;
		w16.Expand = false;
		w16.Fill = false;
		// Container child vbox2.Gtk.Box+BoxChild
		this.hbox1 = new global::Gtk.HBox ();
		this.hbox1.Name = "hbox1";
		this.hbox1.Spacing = 6;
		// Container child hbox1.Gtk.Box+BoxChild
		this.cbSearchFieldType = global::Gtk.ComboBox.NewText ();
		this.cbSearchFieldType.TooltipMarkup = "Fliter search's by flags";
		this.cbSearchFieldType.Name = "cbSearchFieldType";
		this.hbox1.Add (this.cbSearchFieldType);
		global::Gtk.Box.BoxChild w17 = ((global::Gtk.Box.BoxChild)(this.hbox1 [this.cbSearchFieldType]));
		w17.Position = 0;
		w17.Expand = false;
		w17.Fill = false;
		// Container child hbox1.Gtk.Box+BoxChild
		this.searchEntry = new global::Gtk.Entry ();
		this.searchEntry.CanFocus = true;
		this.searchEntry.Name = "searchEntry";
		this.searchEntry.IsEditable = true;
		this.searchEntry.InvisibleChar = '•';
		this.hbox1.Add (this.searchEntry);
		global::Gtk.Box.BoxChild w18 = ((global::Gtk.Box.BoxChild)(this.hbox1 [this.searchEntry]));
		w18.Position = 1;
		// Container child hbox1.Gtk.Box+BoxChild
		this.cbOnlySearchOnColumns = global::Gtk.ComboBox.NewText ();
		this.cbOnlySearchOnColumns.Name = "cbOnlySearchOnColumns";
		this.hbox1.Add (this.cbOnlySearchOnColumns);
		global::Gtk.Box.BoxChild w19 = ((global::Gtk.Box.BoxChild)(this.hbox1 [this.cbOnlySearchOnColumns]));
		w19.Position = 2;
		w19.Expand = false;
		w19.Fill = false;
		this.vbox2.Add (this.hbox1);
		global::Gtk.Box.BoxChild w20 = ((global::Gtk.Box.BoxChild)(this.vbox2 [this.hbox1]));
		w20.Position = 2;
		w20.Expand = false;
		w20.Fill = false;
		this.GtkAlignment1.Add (this.vbox2);
		this.frame1.Add (this.GtkAlignment1);
		this.GtkLabelTitle = new global::Gtk.Label ();
		this.GtkLabelTitle.Name = "GtkLabelTitle";
		this.GtkLabelTitle.Ypad = 5;
		this.GtkLabelTitle.LabelProp = global::Mono.Unix.Catalog.GetString ("<b>All links:</b>");
		this.GtkLabelTitle.UseMarkup = true;
		this.GtkLabelTitle.Justify = ((global::Gtk.Justification)(2));
		this.frame1.LabelWidget = this.GtkLabelTitle;
		this.vbox1.Add (this.frame1);
		global::Gtk.Box.BoxChild w23 = ((global::Gtk.Box.BoxChild)(this.vbox1 [this.frame1]));
		w23.Position = 1;
		this.Add (this.vbox1);
		if ((this.Child != null)) {
			this.Child.ShowAll ();
		}
		this.DefaultWidth = 542;
		this.DefaultHeight = 380;
		this.Show ();
		this.DeleteEvent += new global::Gtk.DeleteEventHandler (this.OnDeleteEvent);
		this.pasteAction.Activated += new global::System.EventHandler (this.onAddLinkAction);
		this.closeAction.Activated += new global::System.EventHandler (this.onRemoveLinkAction);
		this.editLinkAction.Activated += new global::System.EventHandler (this.onEditLinkAction);
		this.editAction1.Activated += new global::System.EventHandler (this.onEditLinkAction);
		this.pasteAction1.Activated += new global::System.EventHandler (this.onAddLinkAction);
		this.editAction2.Activated += new global::System.EventHandler (this.onEditLinkAction);
		this.deleteAction.Activated += new global::System.EventHandler (this.onRemoveLinkAction);
		this.refreshAction1.Activated += new global::System.EventHandler (this.onUpdateDataAction);
		this.btnChooseDb.Clicked += new global::System.EventHandler (this.onBtnChooseDbClicked);
		this.btnShareDB.Clicked += new global::System.EventHandler (this.onShare);
		this.cbSearchFieldType.Changed += new global::System.EventHandler (this.onCbSearchFieldType);
		this.cbSearchFieldType.ButtonReleaseEvent += new global::Gtk.ButtonReleaseEventHandler (this.onCbSearchFieldType);
		this.searchEntry.Activated += new global::System.EventHandler (this.onCbSearchFieldType);
		this.searchEntry.Changed += new global::System.EventHandler (this.onCbSearchFieldType);
		this.cbOnlySearchOnColumns.Changed += new global::System.EventHandler (this.onCbSearchFieldType);
		this.cbOnlySearchOnColumns.ButtonReleaseEvent += new global::Gtk.ButtonReleaseEventHandler (this.onCbSearchFieldType);
	}
}
